services:
  ros:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    devices:
      - ${GPIO_DEVICE:-/dev/gpiomem}:${GPIO_DEVICE:-/dev/gpiomem}
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-14}
      - ROS_LOCALHOST_ONLY=0
      - RMW_IMPLEMENTATION=rmw_fastrtps_dynamic_cpp
    volumes:
      - .:/workspace
      - /dev/shm:/dev/shm # bind host POSIX shm into the container
    working_dir: /workspace
