services:
  tailscale-authkey1:
    build:
      context: .
      dockerfile: Dockerfile.tailscale
    container_name: ts-authkey-test
    hostname: banana
    environment:
      - TS_CLIENT_ID=${TS_CLIENT_ID:-}
      - TS_CLIENT_SECRET=${TS_CLIENT_SECRET:-}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_AUTH_ONCE=true
      - TS_EXTRA_ARGS=--advertise-tags=tag:ros-device --ssh=true
      - TAILSCALE_TAG_NAME=tag:ros-device
    volumes:
      - ts-authkey-test:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
      - .:/workspace
    cap_add:
      - NET_ADMIN
      - NET_RAW
    healthcheck:
      test: ["CMD", "test", "-f", "/workspace/fast.xml"]
      interval: 2s
      timeout: 5s
      retries: 30
      start_period: 10s
  ros:
    build:
      context: .
      dockerfile: Dockerfile
    devices:
      - ${GPIO_DEVICE:-/dev/gpiomem}:${GPIO_DEVICE:-/dev/gpiomem}
    restart: unless-stopped
    network_mode: service:tailscale-authkey1
    depends_on:
      tailscale-authkey1:
        condition: service_healthy
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-14}
      - ROS_LOCALHOST_ONLY=0
      - RMW_IMPLEMENTATION=rmw_fastrtps_dynamic_cpp
    volumes:
      - .:/workspace
      - /dev/shm:/dev/shm # bind host POSIX shm into the container
    working_dir: /workspace

volumes:
  ts-authkey-test:
    driver: local
